title: Military Tech and You
author: Minirals
email: bmccu3@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
 Sexeh as f nukes.
#uwillneverfindme
twitter_username: FUCK NO BOI
github_username:  Minirals

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
